function MAIN()
    % Create the main figure window
    fig = uifigure('Name', 'Writing Score Predictor', ...
                  'Position', [100, 100, 500, 500], ...
                  'Resize', 'off');
    
    % Add title
    titleLabel = uilabel(fig, ...
                        'Text', 'Writing Score Prediction', ...
                        'Position', [125, 460, 250, 30], ...
                        'FontSize', 20, ...
                        'FontWeight', 'bold', ...
                        'HorizontalAlignment', 'center');
    
    % Create input fields
    genderDropDown = uidropdown(fig, ...
                               'Items', {'male', 'female'}, ...
                               'Value', 'male', ...
                               'Position', [250, 400, 200, 30], ...
                               'Tag', 'gender');
    uilabel(fig, 'Text', 'Gender:', 'Position', [100, 400, 100, 30]);
    
    raceDropDown = uidropdown(fig, ...
                             'Items', {'group A', 'group B', 'group C', 'group D', 'group E'}, ...
                             'Value', 'group A', ...
                             'Position', [250, 350, 200, 30], ...
                             'Tag', 'race_ethnicity');
    uilabel(fig, 'Text', 'Race/Ethnicity:', 'Position', [100, 350, 100, 30]);
    
    parentEduDropDown = uidropdown(fig, ...
                                  'Items', {'some high school', 'high school', ...
                                  'some college', 'associate''s degree', ...
                                  'bachelor''s degree', 'master''s degree'}, ...
                                  'Value', 'bachelor''s degree', ...
                                  'Position', [250, 300, 200, 30], ...
                                  'Tag', 'parentEdu');
    uilabel(fig, 'Text', 'Parent Education:', 'Position', [100, 300, 100, 30]);
    
    lunchDropDown = uidropdown(fig, ...
                              'Items', {'standard', 'free/reduced'}, ...
                              'Value', 'standard', ...
                              'Position', [250, 250, 200, 30], ...
                              'Tag', 'lunch');
    uilabel(fig, 'Text', 'Lunch Type:', 'Position', [100, 250, 100, 30]);
    
    testPrepDropDown = uidropdown(fig, ...
                                 'Items', {'none', 'completed'}, ...
                                 'Value', 'none', ...
                                 'Position', [250, 200, 200, 30], ...
                                 'Tag', 'testPrep');
    uilabel(fig, 'Text', 'Test Prep Course:', 'Position', [100, 200, 100, 30]);
    
    mathScoreField = uieditfield(fig, 'numeric', ...
                                'Limits', [0, 100], ...
                                'Value', 70, ...
                                'Position', [250, 150, 200, 30], ...
                                'Tag', 'mathScore');
    uilabel(fig, 'Text', 'Math Score (0-100):', 'Position', [100, 150, 100, 30]);
    
    readingScoreField = uieditfield(fig, 'numeric', ...
                                  'Limits', [0, 100], ...
                                  'Value', 70, ...
                                  'Position', [250, 100, 200, 30], ...
                                  'Tag', 'readingScore');
    uilabel(fig, 'Text', 'Reading Score (0-100):', 'Position', [100, 100, 100, 30]);
    
    % Create predict button
    predictButton = uibutton(fig, ...
                            'Text', 'Predict Writing Score', ...
                            'Position', [175, 50, 150, 30], ...
                            'ButtonPushedFcn', @(btn,event) predictScore(fig));
    
    % Create result label
    resultLabel = uilabel(fig, ...
                         'Text', 'Predicted Score: --', ...
                         'Position', [175, 20, 200, 30], ...
                         'FontSize', 14, ...
                         'FontWeight', 'bold', ...
                         'HorizontalAlignment', 'center', ...
                         'Tag', 'resultLabel');
end

function predictScore(fig)
    % Get values from UI components
    gender = fig.Children.findobj('Tag', 'gender').Value;
    race_ethnicity = fig.Children.findobj('Tag', 'race_ethnicity').Value;
    parentEdu = fig.Children.findobj('Tag', 'parentEdu').Value;
    lunch = fig.Children.findobj('Tag', 'lunch').Value;
    testPrep = fig.Children.findobj('Tag', 'testPrep').Value;
    mathScore = fig.Children.findobj('Tag', 'mathScore').Value;
    readingScore = fig.Children.findobj('Tag', 'readingScore').Value;
    
    % Load the trained model
    load('Gradegueeser.mat');
    trainedModel = Gradegueeser;
    
    % Build the table for prediction
    userData = table( ...
        string(gender), ...
        string(race_ethnicity), ...
        string(parentEdu), ...
        string(lunch), ...
        string(testPrep), ...
        mathScore, ...
        readingScore, ...
        'VariableNames', {'gender','race_ethnicity','parentalLevelOfEducation','lunch','testPreparationCourse','mathScore','readingScore'} ...
    );
    
    % Predict
    predictedWritingScore = trainedModel.predictFcn(userData);
    
    % Update result label
    resultLabel = fig.Children.findobj('Tag', 'resultLabel');
    resultLabel.Text = sprintf('Predicted Writing Score: %.2f out of 100', predictedWritingScore);
    
    % Change color based on score
    if predictedWritingScore >= 80
        resultLabel.FontColor = [0, 0.5, 0]; % Green for high scores
    elseif predictedWritingScore >= 60
        resultLabel.FontColor = [0.8, 0.6, 0]; % Orange for medium scores
    else
        resultLabel.FontColor = [0.8, 0, 0]; % Red for low scores
    end
end